### ISSUE TITLE
前端运行不起来

### ISSUE THREAD

**Issue by chenerzhu** [tokenIsme/quant-admin#1]
前端访问http://localhost:9528 页面空白，F12看调用情况，被302跳转到index.html页面了。请问这个要怎么解决？麻烦看看。。。

**Comment by tokenIsme** [comment]
现在解决了吗？

**Comment by chenerzhu** [comment]
还没，能否抽空帮忙看看，谢谢~

发件人: yang <notifications@github.com>
发送时间: 2019年8月13日 13:06
收件人: tokenIsme/quant-admin <quant-admin@noreply.github.com>
抄送: chenerzhu <chenerzhu@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [tokenIsme/quant-admin] 前端运行不起来 (#1)


现在解决了吗？

**Comment by tokenIsme** [comment]
module.exports = {
  dev: {
    // Paths
    assetsSubDirectory: 'static',
    assetsPublicPath: './',
    proxyTable: {},

    // Various Dev Server settings
    host: 'localhost', // can be overwritten by process.env.HOST
    port: 9528, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
    autoOpenBrowser: true,
    errorOverlay: true,
    notifyOnErrors: false,
    poll: false, // https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-


assetsPublicPath 去掉 . 试试

**Comment by chenerzhu** [comment]
多谢回复。去掉assetsPublicPath: './' 也是空白的。。

________________________________
chenerzhu@hotmail.com

发件人： yang<mailto:notifications@github.com>
发送时间： 2019-08-13 19:37
收件人： tokenIsme/quant-admin<mailto:quant-admin@noreply.github.com>
抄送： chenerzhu<mailto:chenerzhu@hotmail.com>; Author<mailto:author@noreply.github.com>
主题： Re: [tokenIsme/quant-admin] 前端运行不起来 (#1)

module.exports = {
dev: {
// Paths
assetsSubDirectory: 'static',
assetsPublicPath: './',
proxyTable: {},

// Various Dev Server settings
host: 'localhost', // can be overwritten by process.env.HOST
port: 9528, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
autoOpenBrowser: true,
errorOverlay: true,
notifyOnErrors: false,
poll: false, // https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-


assetsPublicPath 去掉 . 试试

**Comment by chenerzhu** [comment]
可以了，是去掉assetsPublicPath: './' 。  是我之前多改了一些。谢谢~

________________________________
chenerzhu@hotmail.com

发件人： yang<mailto:notifications@github.com>
发送时间： 2019-08-13 19:37
收件人： tokenIsme/quant-admin<mailto:quant-admin@noreply.github.com>
抄送： chenerzhu<mailto:chenerzhu@hotmail.com>; Author<mailto:author@noreply.github.com>
主题： Re: [tokenIsme/quant-admin] 前端运行不起来 (#1)

module.exports = {
dev: {
// Paths
assetsSubDirectory: 'static',
assetsPublicPath: './',
proxyTable: {},

// Various Dev Server settings
host: 'localhost', // can be overwritten by process.env.HOST
port: 9528, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
autoOpenBrowser: true,
errorOverlay: true,
notifyOnErrors: false,
poll: false, // https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-


assetsPublicPath 去掉 . 试试

**Comment by tokenIsme** [comment]
不客气
