### ISSUE TITLE
运行起来页面空白呀，，是不是webpack配置问题呢？大佬指点

### ISSUE THREAD

**Issue by youbaocai** [tokenIsme/quant-admin#3]

**Comment by IndexOutOfBounds998** [comment]
看下那个路径 我在那个问题里回答了一个



---原始邮件---
发件人: "youbaocai"<notifications@github.com&gt;
发送时间: 2019年9月16日(星期一) 上午10:27
收件人: "tokenIsme/quant-admin"<quant-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [tokenIsme/quant-admin] 运行起来页面空白呀，，是不是webpack配置问题呢？大佬指点 (#3)



Closed #3.
